name: 'Dustico Analyser'
description: 'This GitHub Action analyses the OSS dependencies via Dustico SaaS platform'
author: 'Dustico'
inputs:
  api_token:
    required: true
    description: "an API token provided by Dustico. contact us at https://dusti.co"
  options:
    required: false
    description: "optional"
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'edit'
  color: 'yellow'
  
  
